### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 1337god**
bad website

### CODE REVIEW

**Comment by nolanlawson** [comment]
What's wrong with `wrongthink.net`? I see they're part of the "pro-1st amendment" GNU Social school of thought, but anything in particular? DM me on Mastodon with the offending toot/toots please. Thanks!

**Comment by nolanlawson** [comment]
On second thought, silencing `wrongthink.net` would be more consistent with our new guidelines outlined in #5. Then again we still allow `maly.io` because I haven't seen anything violating our CoC get boosted into our instance yet, so this is kind of a gray zone. Might need to defer to other moderators' judgment.

**Comment by 1337god** [comment]
yes it's a free speech zone
And https://wrongthink.net/hashtag/killallniggers

**Comment by nolanlawson** [comment]
OK I agree with this decision. Thanks for reporting!

**Pull request closed without merging**
