### PR TITLE
Clarify and update list of blocked instances

### PR DESCRIPTION
**Pull request by nolanlawson**
Updates:

- add `pawoo.net`
- add a table with suspend vs silence status and reason for each instance
- clarify the goals of our community and why we block "free speech zones" and that we have a different cultural heritage than many of the GNU Social instances

To view the formatted Markdown directly, [click here](https://github.com/tootcafe/blocked-instances/blob/3b6b7ae825e9c6dc3b442ae0d9c383154d8e36fb/README.md).

/cc @rachelnicole @halkeye @luisbg @mlcdf

### CODE REVIEW

**Comment by mlcdf** [comment]
What's the difference between silenced and suspended?

**Comment by nolanlawson** [comment]
Silenced means they don't appear in the Federated timeline, but if someone discovers the accounts somehow (e.g. via replying to another toot) then they can follow and it will appear in their Home view.

Note that I've met and I even follow some folks on the silenced instances and many of them seem like fine people. But since I'm cautious I'm okay with keeping them out of the Federated Timeline, for the time being anyway.

**Comment by mlcdf** [comment]
Okay. Well, that sounds good to me!

**Comment by halkeye** [comment]
what does "apparent free speech zone" mean? isn't free speech good?

**Comment by nolanlawson** [comment]
It means they are okay with people promoting National Socialism etc because they believe open discourse is more important than people's sensitivities or the denazification laws of Germany/France/etc.

As someone who's been a rabid libertarian in the past, I can see where they're coming from, but I just don't have those goals for this community.

**Comment by halkeye** [comment]
I'm more saying free speech zone seems like an odd reason to ban someone. I know i didn't know what it meant, so I'm thinking it needs to be clairified a bit more on the PR

**Comment by nolanlawson** [comment]
Good point, I will add a definition.

**Comment by rachelnicole** [comment]
+1

"Free Speech Zones" are usually just garbage fires full of hate.

**Comment by nolanlawson** [comment]
:joy: lol okay let's merge it then. Thanks everyone! I also got a +1 from @luisbg.

**Comment by nolanlawson** [comment]
Fixes https://github.com/tootcafe/discussions/issues/2. If I mis-evaluated an instance please let me know.

**Pull request merged**
